export interface GeographyItem {
  code: string;
  name: string;
}

export const DEPARTAMENTOS: GeographyItem[] = [
  { code: '01', name: 'Ahuachapán' },
  { code: '02', name: 'Santa Ana' },
  { code: '03', name: 'Sonsonate' },
  { code: '04', name: 'Chalatenango' },
  { code: '05', name: 'La Libertad' },
  { code: '06', name: 'San Salvador' },
  { code: '07', name: 'Cuscatlán' },
  { code: '08', name: 'La Paz' },
  { code: '09', name: 'Cabañas' },
  { code: '10', name: 'San Vicente' },
  { code: '11', name: 'Usulután' },
  { code: '12', name: 'San Miguel' },
  { code: '13', name: 'Morazán' },
  { code: '14', name: 'La Unión' }
];

export const MUNICIPIOS: Record<string, GeographyItem[]> = {
  '01': [
    { code: '01', name: 'Ahuachapán' },
    { code: '02', name: 'Jujutla' },
    { code: '03', name: 'Atiquizaya' },
    { code: '04', name: 'Concepción de Ataco' },
    { code: '05', name: 'El Refugio' },
    { code: '06', name: 'Guaymango' },
    { code: '07', name: 'Apaneca' },
    { code: '08', name: 'San Francisco Menéndez' },
    { code: '09', name: 'San Lorenzo' },
    { code: '10', name: 'San Pedro Puxtla' },
    { code: '11', name: 'Tacuba' },
    { code: '12', name: 'Turín' }
  ],
  '02': [
    { code: '01', name: 'Santa Ana' },
    { code: '02', name: 'Candelaria de la Frontera' },
    { code: '03', name: 'Chalchuapa' },
    { code: '04', name: 'Coatepeque' },
    { code: '05', name: 'El Congo' },
    { code: '06', name: 'El Porvenir' },
    { code: '07', name: 'Masahuat' },
    { code: '08', name: 'Metapán' },
    { code: '09', name: 'San Antonio Pajonal' },
    { code: '10', name: 'San Sebastián Salitrillo' },
    { code: '11', name: 'Santa Rosa Guachipilín' },
    { code: '12', name: 'Santiago de la Frontera' },
    { code: '13', name: 'Texistepeque' }
  ],
  '03': [
    { code: '01', name: 'Sonsonate' },
    { code: '02', name: 'Acajutla' },
    { code: '03', name: 'Armenia' },
    { code: '04', name: 'Caluco' },
    { code: '05', name: 'Cuisnahuat' },
    { code: '06', name: 'Izalco' },
    { code: '07', name: 'Juayúa' },
    { code: '08', name: 'Nahuizalco' },
    { code: '09', name: 'Nahulingo' },
    { code: '10', name: 'Salcoatitán' },
    { code: '11', name: 'San Antonio del Monte' },
    { code: '12', name: 'San Julián' },
    { code: '13', name: 'Santa Catarina Masahuat' },
    { code: '14', name: 'Santa Isabel Ishuatán' },
    { code: '15', name: 'Santo Domingo de Guzmán' },
    { code: '16', name: 'Sonzacate' }
  ],
  '04': [
    { code: '01', name: 'Chalatenango' },
    { code: '02', name: 'Agua Caliente' },
    { code: '03', name: 'Arcatao' },
    { code: '04', name: 'Azacualpa' },
    { code: '05', name: 'Citalá' },
    { code: '06', name: 'Comalapa' },
    { code: '07', name: 'Concepción Quezaltepeque' },
    { code: '08', name: 'Dulce Nombre de María' },
    { code: '09', name: 'El Carrizal' },
    { code: '10', name: 'El Paraíso' },
    { code: '11', name: 'La Laguna' },
    { code: '12', name: 'La Palma' },
    { code: '13', name: 'La Reina' },
    { code: '14', name: 'Las Flores' },
    { code: '15', name: 'Las Vueltas' },
    { code: '16', name: 'Nombre de Jesús' },
    { code: '17', name: 'Nueva Concepción' },
    { code: '18', name: 'Nueva Trinidad' },
    { code: '19', name: 'Ojos de Agua' },
    { code: '20', name: 'Potonico' },
    { code: '21', name: 'San Antonio de la Cruz' },
    { code: '22', name: 'San Antonio Los Ranchos' },
    { code: '23', name: 'San Fernando' },
    { code: '24', name: 'San Francisco Lempa' },
    { code: '25', name: 'San Francisco Morazán' },
    { code: '26', name: 'San Ignacio' },
    { code: '27', name: 'San Isidro Labrador' },
    { code: '28', name: 'San Luis del Carmen' },
    { code: '29', name: 'San Miguel de Mercedes' },
    { code: '30', name: 'San Rafael' },
    { code: '31', name: 'Santa Rita' },
    { code: '32', name: 'Tejutla' },
    { code: '33', name: 'El Realejo' }
  ],
  '05': [
    { code: '01', name: 'Nueva San Salvador (Santa Tecla)' },
    { code: '02', name: 'Antiguo Cuscatlán' },
    { code: '03', name: 'Chiltiupán' },
    { code: '04', name: 'Ciudad Arce' },
    { code: '05', name: 'Colón' },
    { code: '06', name: 'Comasagua' },
    { code: '07', name: 'Huizúcar' },
    { code: '08', name: 'Jicalapa' },
    { code: '09', name: 'La Libertad' },
    { code: '10', name: 'Santa Cruz Michapa' },
    { code: '11', name: 'Nuevo Cuscatlán' },
    { code: '12', name: 'San Juan Opico' },
    { code: '13', name: 'Quezaltepeque' },
    { code: '14', name: 'Sacacoyo' },
    { code: '15', name: 'San José Villanueva' },
    { code: '16', name: 'San Matías' },
    { code: '17', name: 'San Pablo Tacachico' },
    { code: '18', name: 'Talnique' },
    { code: '19', name: 'Tamanique' },
    { code: '20', name: 'Teotepeque' },
    { code: '21', name: 'Tepecoyo' },
    { code: '22', name: 'Zaragoza' }
  ],
  '06': [
    { code: '01', name: 'San Salvador' },
    { code: '02', name: 'Ayutuxtepeque' },
    { code: '03', name: 'Mejicanos' },
    { code: '04', name: 'Cuscatancingo' },
    { code: '05', name: 'Delgado' },
    { code: '06', name: 'Soyapango' },
    { code: '07', name: 'Ilopango' },
    { code: '08', name: 'San Martín' },
    { code: '09', name: 'Santiago Texacuangos' },
    { code: '10', name: 'Santo Tomás' },
    { code: '11', name: 'Panchimalco' },
    { code: '12', name: 'Rosario de Mora' },
    { code: '13', name: 'San Marcos' },
    { code: '14', name: 'Nejapa' },
    { code: '15', name: 'Apopa' },
    { code: '16', name: 'Aguilares' },
    { code: '17', name: 'El Paisnal' },
    { code: '18', name: 'Tonacatepeque' },
    { code: '19', name: 'Guazapa' }
  ],
  '07': [
    { code: '01', name: 'Cojutepeque' },
    { code: '02', name: 'Candelaria' },
    { code: '03', name: 'El Carmen' },
    { code: '04', name: 'El Rosario' },
    { code: '05', name: 'Monte San Juan' },
    { code: '06', name: 'Oratorio de Concepción' },
    { code: '07', name: 'San Bartolomé Perulapía' },
    { code: '08', name: 'San Cristóbal' },
    { code: '09', name: 'San José Guayabal' },
    { code: '10', name: 'San Rafael Cedros' },
    { code: '11', name: 'San Ramón' },
    { code: '12', name: 'Santa Cruz Analquito' },
    { code: '13', name: 'Santa Cruz Michapa' },
    { code: '14', name: 'Suchitoto' },
    { code: '15', name: 'Tenancingo' },
    { code: '16', name: 'San Pedro Perulapán' }
  ],
  '08': [
    { code: '01', name: 'Zacatecoluca' },
    { code: '02', name: 'Cuyultitán' },
    { code: '03', name: 'El Rosario' },
    { code: '04', name: 'Jerusalén' },
    { code: '05', name: 'Mercedes La Ceiba' },
    { code: '06', name: 'Olocuilta' },
    { code: '07', name: 'Paraíso de Osorio' },
    { code: '08', name: 'San Antonio Masahuat' },
    { code: '09', name: 'San Emigdio' },
    { code: '10', name: 'San Francisco Chinameca' },
    { code: '11', name: 'San Juan Nonualco' },
    { code: '12', name: 'San Juan Talpa' },
    { code: '13', name: 'San Juan Tepezontes' },
    { code: '14', name: 'San Luis La Herradura' },
    { code: '15', name: 'San Luis Talpa' },
    { code: '16', name: 'San Miguel Tepezontes' },
    { code: '17', name: 'San Pedro Masahuat' },
    { code: '18', name: 'San Pedro Nonualco' },
    { code: '19', name: 'San Rafael Obrajuelo' },
    { code: '20', name: 'Santa María Ostuma' },
    { code: '21', name: 'Santiago Nonualco' },
    { code: '22', name: 'Tapalhuaca' }
  ],
  '09': [
    { code: '01', name: 'Sensuntepeque' },
    { code: '02', name: 'Cinquera' },
    { code: '03', name: 'Dolores' },
    { code: '04', name: 'Guacotecti' },
    { code: '05', name: 'Ilobasco' },
    { code: '06', name: 'Jutiapa' },
    { code: '07', name: 'San Isidro' },
    { code: '08', name: 'Tejutepeque' },
    { code: '09', name: 'Victoria' }
  ],
  '10': [
    { code: '01', name: 'San Vicente' },
    { code: '02', name: 'Apastepeque' },
    { code: '03', name: 'Guadalupe' },
    { code: '04', name: 'San Cayetano Istepeque' },
    { code: '05', name: 'Santa Clara' },
    { code: '06', name: 'Santo Domingo' },
    { code: '07', name: 'Tecoluca' },
    { code: '08', name: 'Tepetitán' },
    { code: '09', name: 'Verapaz' },
    { code: '10', name: 'San Esteban Catarina' },
    { code: '11', name: 'San Ildefonso' },
    { code: '12', name: 'San Lorenzo' },
    { code: '13', name: 'San Sebastián' }
  ],
  '11': [
    { code: '01', name: 'Usulután' },
    { code: '02', name: 'Alegría' },
    { code: '03', name: 'Berlin' },
    { code: '04', name: 'California' },
    { code: '05', name: 'Concepción Batres' },
    { code: '06', name: 'El Triunfo' },
    { code: '07', name: 'Ereguayquín' },
    { code: '08', name: 'Estanzuelas' },
    { code: '09', name: 'Jiquilisco' },
    { code: '10', name: 'Jucuapa' },
    { code: '11', name: 'Jucuarán' },
    { code: '12', name: 'Mercedes Umaña' },
    { code: '13', name: 'Nueva Granada' },
    { code: '14', name: 'Ozatlán' },
    { code: '15', name: 'Puerto El Triunfo' },
    { code: '16', name: 'San Agustín' },
    { code: '17', name: 'San Buenaventura' },
    { code: '18', name: 'San Dionisio' },
    { code: '19', name: 'San Francisco Javier' },
    { code: '20', name: 'Santa Elena' },
    { code: '21', name: 'Santa María' },
    { code: '22', name: 'Santiago de María' },
    { code: '23', name: 'Tecapán' }
  ],
  '12': [
    { code: '01', name: 'San Miguel' },
    { code: '02', name: 'Carolina' },
    { code: '03', name: 'Chapeltique' },
    { code: '04', name: 'Chinameca' },
    { code: '05', name: 'Chirilagua' },
    { code: '06', name: 'Ciudad Barrios' },
    { code: '07', name: 'Comacarán' },
    { code: '08', name: 'El Tránsito' },
    { code: '09', name: 'Lolotique' },
    { code: '10', name: 'Moncagua' },
    { code: '11', name: 'Nueva Guadalupe' },
    { code: '12', name: 'Nuevo Edén de San Juan' },
    { code: '13', name: 'Quelepa' },
    { code: '14', name: 'San Antonio del Mosco' },
    { code: '15', name: 'San Gerardo' },
    { code: '16', name: 'San Jorge' },
    { code: '17', name: 'San Luis de la Reina' },
    { code: '18', name: 'San Rafael Oriente' },
    { code: '19', name: 'Sesori' },
    { code: '20', name: 'Uluazapa' }
  ],
  '13': [
    { code: '01', name: 'San Francisco Gotera' },
    { code: '02', name: 'Arambala' },
    { code: '03', name: 'Cacaopera' },
    { code: '04', name: 'Chilanga' },
    { code: '05', name: 'Corinto' },
    { code: '06', name: 'Delicias de Concepción' },
    { code: '07', name: 'El Divisadero' },
    { code: '08', name: 'El Rosario' },
    { code: '09', name: 'Gualococti' },
    { code: '10', name: 'Guatajiagua' },
    { code: '11', name: 'Joateca' },
    { code: '12', name: 'Jocoaitique' },
    { code: '13', name: 'Jocoro' },
    { code: '14', name: 'Lolotiquillo' },
    { code: '15', name: 'Meanguera' },
    { code: '16', name: 'Osicala' },
    { code: '17', name: 'Perquín' },
    { code: '18', name: 'San Carlos' },
    { code: '19', name: 'San Fernando' },
    { code: '20', name: 'San Isidro' },
    { code: '21', name: 'San Simón' },
    { code: '22', name: 'Sensembra' },
    { code: '23', name: 'Sociedad' },
    { code: '24', name: 'Torola' },
    { code: '25', name: 'Yamabal' },
    { code: '26', name: 'Yoloaiquín' }
  ],
  '14': [
    { code: '01', name: 'La Unión' },
    { code: '02', name: 'Anamorós' },
    { code: '03', name: 'Bolivar' },
    { code: '04', name: 'Concepción de Oriente' },
    { code: '05', name: 'Conchagua' },
    { code: '06', name: 'El Carmen' },
    { code: '07', name: 'El Sauce' },
    { code: '08', name: 'Intipucá' },
    { code: '09', name: 'Lislique' },
    { code: '10', name: 'Meanguera del Golfo' },
    { code: '11', name: 'Nueva Esparta' },
    { code: '12', name: 'Pasaquina' },
    { code: '13', name: 'Polorós' },
    { code: '14', name: 'San Alejo' },
    { code: '15', name: 'San José' },
    { code: '16', name: 'Santa Rosa de Lima' },
    { code: '17', name: 'Yayantique' },
    { code: '18', name: 'Yucuaiquín' }
  ]
};
