/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthResponse { 
    token?: string;
    refreshToken?: string;
    type?: string;
    id?: number;
    username?: string;
    name?: string;
    role?: string;
    tenantId?: number;
    branchId?: number;
    branchName?: string;
}

