/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerDto { 
    id?: number;
    name?: string;
    nit?: string;
    email?: string;
    phone?: string;
    nrc?: string;
    giro?: string;
    documentType?: string;
    documentNumber?: string;
    departamento?: string;
    municipio?: string;
    complemento?: string;
}

