/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';


export interface Customer { 
    id?: number;
    name?: string;
    phone?: string;
    email?: string;
    nit?: string;
    tenant?: Tenant;
}

