/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { Product } from './product';


export interface DashboardSummaryResponse { 
    todaySales?: number;
    availableTables?: number;
    occupiedTables?: number;
    activeOrdersCount?: number;
    lowStockProducts?: Array<Product>;
    recentOrders?: Array<Order>;
}

