/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Customer } from './customer';


export interface Invoice { 
    id?: number;
    subtotal?: number;
    tax?: number;
    total?: number;
    paymentMethod?: string;
    issuedAt?: string;
    customer?: Customer;
    dteType?: string;
    generationCode?: string;
    controlNumber?: string;
    receptionSello?: string;
}

