/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KitchenItemResponse } from './kitchenItemResponse';


export interface KitchenOrderResponse { 
    id?: number;
    tableNumber?: string;
    waiterName?: string;
    status?: string;
    createdAt?: string;
    minutesElapsed?: number;
    items?: Array<KitchenItemResponse>;
}

