/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { Product } from './product';


export interface OrderItem { 
    id?: number;
    quantity?: number;
    unitPrice?: number;
    subtotal?: number;
    notes?: string;
    status?: string;
    order?: Order;
    product?: Product;
}

