/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Invoice } from './invoice';
import { User } from './user';
import { Customer } from './customer';
import { RestaurantTable } from './restaurantTable';
import { Branch } from './branch';
import { OrderItem } from './orderItem';


export interface Order { 
    id?: number;
    consecutiveNumber?: number;
    status?: string;
    total?: number;
    discountType?: string;
    discountValue?: number;
    createdAt?: string;
    updatedAt?: string;
    restaurantTable?: RestaurantTable;
    user?: User;
    branch?: Branch;
    customer?: Customer;
    items?: Array<OrderItem>;
    invoice?: Invoice;
}

