/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PermissionResponse { 
    id?: number;
    component?: string;
    canRead?: boolean;
    canWrite?: boolean;
    canDelete?: boolean;
}

