/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Tenant } from './tenant';


export interface Product { 
    id?: number;
    name?: string;
    description?: string;
    price?: number;
    isAvailable?: boolean;
    quantity?: number;
    minStock?: number;
    imageUrl?: string;
    isSellable?: boolean;
    category?: Category;
    tenant?: Tenant;
}

