/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Response { 
    id?: number;
    status?: string;
    openingAmount?: number;
    openedAt?: string;
    openedByName?: string;
    closingAmount?: number;
    closedAt?: string;
    closedByName?: string;
    totalCash?: number;
    totalCard?: number;
    totalTransfer?: number;
    totalSales?: number;
    difference?: number;
    notes?: string;
    branchName?: string;
}

