/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Branch } from './branch';


export interface RestaurantTable { 
    id?: number;
    number?: number;
    status?: string;
    capacity?: number;
    posX?: number;
    posY?: number;
    branch?: Branch;
}

