/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';
import { RolePermission } from './rolePermission';


export interface Role { 
    id?: number;
    name?: string;
    description?: string;
    tenant?: Tenant;
    permissions?: Array<RolePermission>;
}

