/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentMethodBreakdown } from './paymentMethodBreakdown';
import { DailySales } from './dailySales';
import { WaiterSales } from './waiterSales';
import { ProductSales } from './productSales';


export interface SalesReportResponse { 
    totalRevenue?: number;
    totalTax?: number;
    totalSubtotal?: number;
    totalInvoices?: number;
    averageTicket?: number;
    dailySales?: Array<DailySales>;
    revenueByHour?: { [key: string]: number; };
    topProducts?: Array<ProductSales>;
    paymentMethods?: Array<PaymentMethodBreakdown>;
    topWaiters?: Array<WaiterSales>;
}

