/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RoleConfigRequest } from './roleConfigRequest';


export interface SetupWizardRequest { 
    companyName?: string;
    domain?: string;
    currency?: string;
    currencySymbol?: string;
    branchName?: string;
    branchAddress?: string;
    branchPhone?: string;
    adminName?: string;
    adminUsername?: string;
    adminPassword?: string;
    roles?: Array<RoleConfigRequest>;
}

