/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Inventory } from './inventory';


export interface StockMovement { 
    id?: number;
    inventory?: Inventory;
    movementType?: StockMovement.MovementTypeEnum;
    quantity?: number;
    reason?: string;
    createdBy?: User;
    createdAt?: string;
}
export namespace StockMovement {
    export const MovementTypeEnum = {
        In: 'IN',
        Out: 'OUT',
        Adjustment: 'ADJUSTMENT'
    } as const;
    export type MovementTypeEnum = typeof MovementTypeEnum[keyof typeof MovementTypeEnum];
}


