/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';


export interface Tax { 
    id?: number;
    name?: string;
    percentage?: number;
    isActive?: boolean;
    type?: 'STANDARD' | 'TIP' | 'RETENTION';
    tenant?: Tenant;
}

