/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Tenant { 
    id?: number;
    name?: string;
    domain?: string;
    currency?: string;
    currencySymbol?: string;
    nit?: string;
    nrc?: string;
    giro?: string;
    isActive?: boolean;
    stockMultiplier?: number;
    createdAt?: string;
}

