/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { Tenant } from './tenant';
import { Branch } from './branch';


export interface User { 
    id?: number;
    username: string;
    password: string;
    name: string;
    role?: Role;
    isActive?: boolean;
    tenant?: Tenant;
    branch?: Branch;
}

